imports:
- path: bigtable.jinja

resources:
- name: my-bigtable
  type: bigtable.jinja
  properties:
    zone: us-central1-b
    columnFamilies:
      col1:
        gcRule:
          maxNumVersions: 2
      col2:
        gcRule:
          maxNumVersions: 2
